[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "W", "UP", "B", "S", "PL"]
ignore = []

[tool.ruff.lint.per-file-ignores]
"cli.py" = ["S101"]

[tool.pytest.ini_options]
pythonpath = ["."]
